name: Docker Image CI

on:
  push:
    branches: [master]

jobs:

  build_superset:
    # if: startsWith(github.ref, 'refs/tags/superset-')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Get tag
      run: |
        TAG=${GITHUB_REF_NAME#superset-}
        echo "tag=${TAG}"
        echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
    - name: Build and push
      run: echo ${{ env.IMAGE_TAG }}
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: superset
    #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/superset:${IMAGE_TAG}
    #     push: true
