name: Docker Image CI

on:
  push:
   branches:
     - master
   paths:
     - golangci/**
     - superset/**
     - hugo-nginx/**

jobs:

  build_and_push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        images: [golangci, superset, hugo-nginx]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Get tag
      run: |
        TAG=$(echo -n "${{ github.event.commits[0].message }}" | grep -oP '(?<=${{ matrix.images }}:)([0-9.]*)') || true
        echo "tag=${TAG}"
        echo "IMAGE_TAG=${TAG}" >> $GITHUB_ENV
    - name: Build and push
      if: ${{ env.IMAGE_TAG }}
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.images }}
        file: ${{ matrix.images }}/Dockerfile
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.images }}:${{ env.IMAGE_TAG }}
        push: true
